### PR TITLE
Fixed wrong writePosition being used for EmbeddedBytes

### LINKED ISSUE #422: Embedded bytes can't be cleared after TriviallyCopyable unmarshalling
The bug is that `AbstractBytes#writePosition` used as field somewhere, while it's overridden in `EmbeddedBytes`:
```
    @Override
    public @NonNegative long writePosition() {
        return bytesStore.readUnsignedByte(bytesStore.start() - 1);
    }
```
So we end up using wrong `writePosition` in some cases. 
Test:
```
    @Test
    public void testClear() {
        ClassAliasPool.CLASS_ALIASES.addAlias(EBM.class);
        EBM e1 = new EBM();
        e1.a.append("a12345678");
        Bytes<?> bytes = Bytes.allocateElasticOnHeap();
        e1.writeMarshallable(bytes);

        EBM e2 = new EBM();
        e2.readMarshallable(bytes);
        e2.a.clear();
        e2.a.append("b0000000");

        Assert.assertEquals("b0000000", e2.a.toString());

        bytes.releaseLast();
    }
```
Currently, `clear()` does nothing - because of this fast path check:
```
    public Bytes<U> clear()
            throws IllegalStateException {
        final long start = start();
        final long capacity = capacity();
        if (readPosition == start && writePosition == start && writeLimit == capacity) 
            return this;
```

### PR DESCRIPTION
**Pull request by glukos**
See also https://github.com/OpenHFT/Chronicle-Wire/pull/549 - reproducing test

### CODE REVIEW

**Review by JerryShea — APPROVED** [review]

File: src/main/java/net/openhft/chronicle/bytes/AbstractBytes.java [hunk 1]
```diff
@@ -133,7 +133,7 @@ public Bytes<U> clear()
             throws IllegalStateException {
         final long start = start();
         final long capacity = capacity();
-        if (readPosition == start && writePosition == start && writeLimit == capacity)
+        if (readPosition == start && writePosition() == start && writeLimit == capacity)
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/bytes/AbstractBytes.java:137]: Good find, I wonder if it's feasible to/worth making `writePosition` private to reduce the number of places a bug like this can be reintroduced going forward?

**Review by nicktindall — APPROVED** [review]

File: src/main/java/net/openhft/chronicle/bytes/AbstractBytes.java (hunk 1 above)
Comment (glukos) [reply src/main/java/net/openhft/chronicle/bytes/AbstractBytes.java:137]: Good point.
It's a compatibility break to make this change right away - I've left a comment to do it in x.24
