### PR TITLE
Resolve suspicious method UncheckedBytes::write, Fix #230

### LINKED ISSUE #230: Remove unsafe method UncheckedBytes::write
Currently, this method looks like this:

```
    @Override
    public void write(long offsetInRDO, ByteBuffer bytes, int offset, int length)
            throws BufferOverflowException {

    }
```

but it is more likely that it should be like this:

```
    @Override
    public void write(long offsetInRDO, ByteBuffer bytes, int offset, int length)
            throws BufferOverflowException {
        bytesStore.write(offsetInRDO, bytes, offset, length);
    }
```

### PR DESCRIPTION
**Pull request by minborg**
It appears that we missed doing something in this method.

### CODE REVIEW

File: src/main/java/net/openhft/chronicle/bytes/UncheckedBytes.java [hunk 1]
```diff
@@ -309,6 +309,7 @@ void append8bit(char[] chars)
     @Override
     public void write(long offsetInRDO, ByteBuffer bytes, int offset, int length)
             throws BufferOverflowException {
-
+        // Todo: Optimize this
```
Comment (JerryShea) [inline src/main/java/net/openhft/chronicle/bytes/UncheckedBytes.java:312]: great catch. We should have a test? :)

**Review by JerryShea — APPROVED** [review]
